### ISSUE TITLE
Add linkspeed to network interface tables

### ISSUE THREAD

**Issue by donjuanal** [r-Techsupport/Get-Specs#107]
Adding the linkspeed to the listed network interfaces will be helpful in troubleshooting negotiation and linkspeed issues. It can be obtained with `Get-NetAdapter | select linkspeed`, though I'm sure the implementation will be slightly different. It will show wireless linkspeed at the time of the command being run as well as ethernet negotiated linkspeed.

**Comment by PipeItToDevNull** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/25917750/183779262-d469920a-70bd-408b-b6ac-7074eb155865.png">
