### ISSUE TITLE
Exit button doesn't work

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/Get-Specs#123]
Likely because the scripts are split now, it isn't really needed so remove it

**Comment by TheKrol** [comment]
![image](https://user-images.githubusercontent.com/7559922/187529529-ad6ba59c-e4ca-47db-8087-1532117bd313.png)
Changing Exit to break worked for me.

**Comment by K97i** [comment]
Tried Krol's solution myself, it does indeed work
