### ISSUE TITLE
Powershell opens to ask to change excution policy

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/Get-Specs#131]
![image](https://user-images.githubusercontent.com/7559922/193416782-ee7ca063-a249-4a75-82ee-59cea649fa4b.png)
On a new machine, when you pass UAC powershell will ask you to change the policy before it opens the prompt to start, tested on windows 10 VM

**Comment by PipeItToDevNull** [comment]
We dont have any users hit this issue, so I assume this is not widespread
