### ISSUE TITLE
Add detection for optimization software

### ISSUE THREAD

**Issue by m6qh9mkyn9** [r-Techsupport/Get-Specs#132]
Scan for process name 
Process Lasso Core (Process Governor)
along with the running process of 
C:\Program Files\Process Lasso\bitsumsessionagent.exe
C:\Program Files\Process Lasso\processlasso.exe
C:\Program Files\Process Lasso\processgovernor.exe
This is from the optimization software process lasso which attempts to make the system faster by throttling everything excessively, most users fail to whitelist all their applications resulting in issues.

**Comment by PipeItToDevNull** [comment]
Is no program seen as installed?
