### ISSUE TITLE
Implement `Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -match '^USB' }` for a list of USB device details

### ISSUE THREAD

**Issue by zleyyij** [r-Techsupport/Get-Specs#134]
windows equivalent of `lsusb`

**Comment by PipeItToDevNull** [comment]
```
Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -match '^USB' } | Select FriendlyName,Description,Class,InstanceID,PNPClass,Status
```

Is this enough of the fields?

**Comment by zleyyij** [comment]
Throw `Service` in the list, and that's fantastic, thanks

**Comment by PipeItToDevNull** [comment]
`Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -match '^USB' } | Select FriendlyName,Description,Class,InstanceID,Status,Service`

**Comment by PipeItToDevNull** [comment]
![image](https://user-images.githubusercontent.com/25917750/197391611-229c8bda-d260-4b76-be2e-fbf8b7bc8311.png)
