### ISSUE TITLE
somehow attach a battery report to the results for laptops, maybe as a seperate paste

### ISSUE THREAD

**Issue by zleyyij** [r-Techsupport/Get-Specs#135]

**Comment by PipeItToDevNull** [comment]
How is one generated?

**Comment by zleyyij** [comment]
`powercfg /batteryreport` [writes an html file to the user's home directory](https://support.microsoft.com/en-us/windows/caring-for-your-battery-in-windows-2db3e37f-5e7d-488e-9086-ed15320519e4). This generates a html file in the user's home directory. It generates the file regardless of whether or not the system actually has a battery, so you would need a way to differentiate between a laptop and desktop, ideally the report would not be included on desktop systems.

**Comment by TheKrol** [comment]
[BatteryTest.txt](https://github.com/r-Techsupport/Get-Specs/files/10214645/BatteryTest.txt)
