### ISSUE TITLE
Updating Monitor info to work better 

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/Get-Specs#152]
[Monitortest.txt](https://github.com/r-Techsupport/Get-Specs/files/10115844/Monitortest.txt)

**Comment by TheKrol** [comment]
[MonitorInfo.txt](https://github.com/r-Techsupport/Get-Specs/files/10163764/MonitorInfo.txt)
Update to use dxdiag, and output is looking good on laptops now

**Comment by PipeItToDevNull** [comment]
f478fa2d6ab94dd440870e2ca2c415c8a30e0370
