### ISSUE TITLE
Add TCP Adapter Global Settings Check

### ISSUE THREAD

**Issue by m6qh9mkyn9** [r-Techsupport/Get-Specs#43]
netsh int tcp show global
The top two options should be as following, otherwise it will aversely affect the ethernet speed of the PC. This is caused by some software I have yet to track down. 
Receive-Side Scaling State          : enabled
Receive Window Auto-Tuning Level    : normal
?tcpreset can be used on the server to remedy the issue.

**Comment by m6qh9mkyn9** [comment]
Its Get-NetTCPSetting

**Comment by PipeItToDevNull** [comment]
PS doesn't work, need to make an object from the dos output

**Comment by TheKrol** [comment]
![image](https://user-images.githubusercontent.com/7559922/176337997-f1b14bda-dca2-4838-b9e9-0277d0b620aa.png)

Commands used:

$ReceiveSideScaling = Get-NetOffloadGlobalSetting | ConvertTo-Html ReceiveSideScaling -Fragment -PreContent "<h2 class='collapsible'> Receive Side Scaling</h2>"

$AutoTuning = Get-NetTCPSetting | ConvertTo-Html SettingName,Autotuninglevellocal -Fragment -PreContent "<h2 class='collapsible'> Auto Tuning Level Local</h2>"
