### ISSUE TITLE
Fastboot check

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/Get-Specs#5]

**Comment by SealsRock12** [comment]
Would you note whether it is enabled or disabled?

**Comment by PipeItToDevNull** [comment]
Likely add it into some section to report on all statuses, not a note

**Comment by m6qh9mkyn9** [comment]
Reg Query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power" /v HiberBootEnabled
1 is on
0 is off

**Comment by PipeItToDevNull** [comment]
```
 Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power" | Select-Object -ExpandProperty HiberbootEnabled
 ```
