### ISSUE TITLE
Validate C: and the ESP are on the same disk

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/Get-Specs#7]
This would be a 'known issue' because the OS is dependent on 2 disks

**Comment by TheKrol** [comment]
get-partition | where-object {$_.GptType -eq "{C12A7328-F81F-11D2-BA4B-00A0C93EC93B}"}

It seems like this could get it, not sure yet how you can use it to compare.

**Comment by PipeItToDevNull** [comment]
That actually returns Disk # as well, that is helpful

**Comment by PipeItToDevNull** [comment]
```
If ($(Get-Partition | ? {$_.GptType -eq "{C12A7328-F81F-11D2-BA4B-00A0C93EC93B}"}).DiskNumber -eq $(Get-Partition | ? {$_.DriveLetter -eq "C" }).DiskNumber) { Write-Host 'yay' }
```
