### ISSUE TITLE
validate TPM and secure boot for Windows 11

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/Get-Specs#77]

**Comment by SealsRock12** [comment]
I'll try

**Comment by SealsRock12** [comment]
Will we remove the registry key check if we do this?

**Comment by PipeItToDevNull** [comment]
no, the reason this is required is because some machines are bypassing it without the registry change. I saw a report that had this issue

**Comment by PipeItToDevNull** [comment]
yeah, I need to test still
