### ISSUE TITLE
sort procs alphabetically for Don

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/Get-Specs#83]

**Comment by TheKrol** [comment]
Line 770 `$2 = $runningProcesses | Select -Unique | Select $properties | Sort-Object Name | ConvertTo-Html -Fragment`

Sample output:
![image](https://user-images.githubusercontent.com/7559922/178104576-57e34a2f-31f4-4a66-ba4f-4d1f186baba2.png)
