### ISSUE TITLE
Check C and ESP method

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/Get-Specs#97]
Check method for C and ESP. It showed up wrong with only one disk
[tya64n9z.txt](https://github.com/r-Techsupport/Get-Specs/files/9226818/tya64n9z.txt)
.

**Comment by PipeItToDevNull** [comment]
SealsRock12: The C/ESP on same disk check doesn't work if you have two partitions with ESP's

**Comment by PipeItToDevNull** [comment]
9:36 PM] SealsRock12: @Krol | a Chuckle Fuck maybe what might help is checking whether the disk where C:\ resides has an ESP or not
[9:36 PM] SealsRock12: it is possible that it does but the ESP used for windows is on a different disk, but that's less likely

**Comment by SealsRock12** [comment]
Closed in #118
